name:                eff-prelude
version:             0.1.0.0
github:              "cardenaso11/eff-prelude"
license:             BSD3
author:              "Nicholas Cardenas"
maintainer:          "nicholas.cardenas.1@gmail.com"
copyright:           "Nicholas Cardenas"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Effect based prelude for Haskell. <https://github.com/githubuser/eff-prelude#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - freer-simple
  - random

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- ConstraintKinds
- DataKinds
- DeriveFunctor
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- LambdaCase
- MultiParamTypeClasses
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeOperators

executables:
  eff-prelude-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eff-prelude

tests:
  eff-prelude-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eff-prelude
